### ISSUE TITLE
Unable to set Video mode, Format and Frame rate using pyfly2.Context.set_mode()

### ISSUE THREAD

**Issue by JoosMax** [kbrafford/pyfly2#10]
First of all, thank you very much for sharing your work.
I've been able to communicate to my camera (Flea3 FL3-U3-13S2M), set properties (shutter for example), but so far I had no success in setting the frame rate using Context.set_mode(_a_, _b_) where _a_ and _b_ are integer corresponding to the desired VideoMode and FrameRate.

for example : 
>>context.get_mode()

>(23, 8)

but

>>context.set_mode(23,8)

>Traceback (most recent call last):
File "<ipython-input-31-01bf8728041b>", line 1, in <module>
context.set_mode(23,8)
File "pyfly2.pyx", line 512, in pyfly2.Context.set_mode (pyfly2.c:6120)
File "pyfly2.pyx", line 133, in pyfly2.errcheck (pyfly2.c:1653)
FC2Error: 'IIDC failure.'

I was wondering if anyone was able to use context.set_mode() properly.

Best regards,
Maxime Joos

**Comment by lgrossman** [comment]
I also am having this problem.

**Comment by JoosMax** [comment]
Point Grey (FLIR) finally released a python wrapper called pyCapture, that actually solve the various problems:

https://www.ptgrey.com/support/downloads

**Comment by kbrafford** [comment]
I have been meaning to check out their official python support.  Glad to see them embrace it finally!
